version: "3.11"

services:
  web:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s # default
        max_attempts: 5
    build: .
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DB_USER=devuser
      - DB_NAME=devdb
      - DB_PASS=dimadom
      - DB_HOST=172.24.0.2
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
        # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/regions.csv:/docker-entrypoint-initdb.d/regions.csv
      - ./sql/prices.csv:/docker-entrypoint-initdb.d/prices.csv
      - ./sql/ports.csv:/docker-entrypoint-initdb.d/ports.csv
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=dimadom
    ports:
      - "6543:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  dev-db-data: